### ISSUE TITLE
Observed "com.hazelcast.core.HazelcastException: No invocation for response" when running driver and server on separate host

### ISSUE THREAD

**Issue by rdiyewar** [gridgain/yardstick-hazelcast#2]
I tried running this benchmark. When i ran everything (all servers and driver) on localhost, it worked fine. However, when i ran server and driver on separate machines, it failed with folliwing Exception.

```
Jun 05, 2015 1:01:05 PM com.hazelcast.spi.OperationService
SEVERE: [10.112.204.215]:57500 [dev] [3.4.2] While processing response...
com.hazelcast.core.HazelcastException: No invocation for response: NormalResponse{callId=17592, urgent=false, value=null, backupCount=0}
        at com.hazelcast.spi.impl.BasicOperationService$ResponsePacketHandler.notifyRemoteCall(BasicOperationService.java:618)
        at com.hazelcast.spi.impl.BasicOperationService$ResponsePacketHandler.handle(BasicOperationService.java:602)
        at com.hazelcast.spi.impl.BasicOperationService$ResponsePacketHandler.access$1300(BasicOperationService.java:595)
        at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:580)
        at com.hazelcast.spi.impl.BasicOperationScheduler$ResponseThread.process(BasicOperationScheduler.java:532)
        at com.hazelcast.spi.impl.BasicOperationScheduler$ResponseThread.doRun(BasicOperationScheduler.java:524)
        at com.hazelcast.spi.impl.BasicOperationScheduler$ResponseThread.run(BasicOperationScheduler.java:501)

Finishing main test [ts=1433489465543, date=Fri Jun 05 13:01:05 IST 2015]
ERROR: Shutting down benchmark driver to unexpected exception.
Type '--help' for usage.
com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:mapService', op=PutOperation{map}, partitionId=149, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.112.204.211]:57500, backupsExpected=0, backupsCompleted=0}, response=null, done=false} No response has been received!  backups-expected:0 backups-completed: 0
        at com.hazelcast.spi.impl.BasicInvocationFuture.newOperationTimeoutException(BasicInvocationFuture.java:309)
        at com.hazelcast.spi.impl.BasicInvocation.handleOperationTimeout(BasicInvocation.java:558)
        at com.hazelcast.spi.impl.BasicPartitionInvocation.handleOperationTimeout(BasicPartitionInvocation.java:28)
        at com.hazelcast.spi.impl.BasicOperationService$CleanupThread.scanHandleOperationTimeout(BasicOperationService.java:1135)
        at com.hazelcast.spi.impl.BasicOperationService$CleanupThread.run(BasicOperationService.java:1102)
        at ------ End remote and begin local stack-trace ------.(Unknown Source)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:387)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:320)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:194)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:173)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:416)
        at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:365)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:102)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:89)
        at org.yardstickframework.hazelcast.HazelcastPutBenchmark.test(HazelcastPutBenchmark.java:32)
        at org.yardstickframework.impl.BenchmarkRunner$2.run(BenchmarkRunner.java:165)
        at java.lang.Thread.run(Thread.java:745)
```

Have you encountered this earlier? How to resolve it?

**Comment by yardstick-benchmarks** [comment]
Hi,
This looks like a network issue. Could you provide logs from all nodes?

**Comment by niktikhonov** [comment]
Hi,
This looks like a connectivity issue.Could you provide full logs from all nodes?

**Comment by rdiyewar** [comment]
Please find logs at https://github.com/rdiyewar/junk/tree/master/hazelcast-issue2/logs-20150605-145327

**Comment by niktikhonov** [comment]
Thanks! From your log see that you have stable topology (4 nodes where 2 nodes working on the same host). Remote node ((Address[10.112.204.211]:57500)) which did not respond to driver does not contain errors, warns in log. Could you start nodes with debug? (http://docs.hazelcast.org/docs/latest/manual/html/faq.html section "How can I see debug level logs") Do you get this error stable for each run?
