### ISSUE TITLE
Failed to set up benchmark drivers with lite client

### ISSUE THREAD

**Issue by isuntsov-gridgain** [gridgain/yardstick-hazelcast#8]
I've started sql-query set benchmark with 4 servers and 8 clients (-nt LITE_MEMBER) and got the following exception:

```
com.hazelcast.partition.NoDataMemberInClusterException: Partitions can't be assigned since all nodes in the cluster are lite members
<------>at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getPartitionOwnerOrWait(InternalPartitionServiceImpl.java:207)
<------>at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getMemberPartitionsMap(InternalPartitionServiceImpl.java:887)
<------>at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:369)
<------>at com.hazelcast.map.impl.proxy.MapProxySupport.addIndex(MapProxySupport.java:1099)
<------>at com.hazelcast.map.impl.proxy.MapProxyImpl.addIndex(MapProxyImpl.java:102)
<------>at com.hazelcast.map.impl.proxy.MapProxySupport.initializeIndexes(MapProxySupport.java:230)
<------>at com.hazelcast.map.impl.proxy.MapProxySupport.initialize(MapProxySupport.java:213)
<------>at com.hazelcast.map.impl.proxy.MapProxyImpl.initialize(MapProxyImpl.java:102)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:177)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:167)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:136)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:147)
<------>at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:380)
<------>at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:186)
<------>at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:96)
<------>at org.yardstickframework.hazelcast.HazelcastAbstractBenchmark.setUp(HazelcastAbstractBenchmark.java:66)
<------>at org.yardstickframework.hazelcast.HazelcastSqlQuerySetBenchmark.setUp(HazelcastSqlQuerySetBenchmark.java:45)
<------>at org.yardstickframework.BenchmarkDriverStartUp.main(BenchmarkDriverStartUp.java:130)

<14:01:07><main><yardstick> Failed to set up benchmark drivers (will shutdown and exit).
com.hazelcast.partition.NoDataMemberInClusterException: Partitions can't be assigned since all nodes in the cluster are lite members
<------>at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getPartitionOwnerOrWait(InternalPartitionServiceImpl.java:207)
<------>at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getMemberPartitionsMap(InternalPartitionServiceImpl.java:887)
<------>at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:369)
<------>at com.hazelcast.map.impl.proxy.MapProxySupport.addIndex(MapProxySupport.java:1099)
<------>at com.hazelcast.map.impl.proxy.MapProxyImpl.addIndex(MapProxyImpl.java:102)
<------>at com.hazelcast.map.impl.proxy.MapProxySupport.initializeIndexes(MapProxySupport.java:230)
<------>at com.hazelcast.map.impl.proxy.MapProxySupport.initialize(MapProxySupport.java:213)
<------>at com.hazelcast.map.impl.proxy.MapProxyImpl.initialize(MapProxyImpl.java:102)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:177)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:167)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:136)
<------>at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:147)
<------>at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:380)
<------>at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:186)
<------>at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:96)
<------>at org.yardstickframework.hazelcast.HazelcastAbstractBenchmark.setUp(HazelcastAbstractBenchmark.java:66)
<------>at org.yardstickframework.hazelcast.HazelcastSqlQuerySetBenchmark.setUp(HazelcastSqlQuerySetBenchmark.java:45)
<------>at org.yardstickframework.BenchmarkDriverStartUp.main(BenchmarkDriverStartUp.java:130)
<14:01:07><main><yardstick> Finished sql query put benchmark [putCnt=0, qryCnt=0]

```

Looks like client didn't find any server and client process was killed

**Comment by ntikhonov** [comment]
@isuntsov-gridgain ,
I've fixed it, please recheck.
